volumes:
  movie_data:
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: MovieDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - movie_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8280:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
      